baseurl = "https://www.stefanoteodorani.it/"
# https://www.fincher.org/Utilities/CountryLanguageList.shtml
languageCode = "es-419"
DefaultContentLanguage = "fr"
title = "stefanoteodorani.it"
# Enable comments by entering your Disqus shortname
disqusShortname = "stefanoteodorani"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 5
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
publishDir = "docs"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  # Tell me who you are
  author = "Stefano Teodorani"
  bio = "DBA, Programmer, Linux Administrator and Opensource lover"
  location = "Savignano sul Rubicone"
  site_description = ""
  copyright  = "Powered by [Hugo](//gohugo.io)"
  avatar = "https://avatars0.githubusercontent.com/u/2573389?v=3&s=460"
  # https://github.com/digitalcraftsman/hugo-icarus-theme
  logo = "css/images/logo.png"
  disable_mathjax = true # set to true to disable MathJax

  # Format dates with Go's time formatting
  # https://golang.org/src/time/format.go
  #date_format = "2006-01-02"
  date_format = "02-01-2006"

    # Add custom assets with their paths relative to the static folder
  custom_css = ["css/button.css", "css/notice.css"]
  custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

#[[params.menu]]
#    before = false
#    label  = "About me"
#    link   = "aboutme/"

[[params.menu]]
    before = false
    label  = "My Dog"
    link   = "http://teopost.github.io/ulisse"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/teopost"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "teopost"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "teopost"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "stefano-teodorani-58722b70/"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = "StefanoTeodorani"
    facebook        = "steodorani"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "teopost"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = false


# Privacy
privacy_pack = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = false
